services:
  - type: web
    name: farmacia-bienestar
    env: node
    plan: free

    buildCommand: |
      # Backend
      cd backBien
      npm install

      # Frontend
      cd ../frontFarm
      npm install
      npm run build -- --configuration production

      echo "===== Contenido de dist ====="
      ls -R dist

      mkdir -p ../backBien/public
      cp -r dist/front-farm/* ../backBien/public/

      echo "===== Contenido final en backBien/public ====="
      ls -R ../backBien/public

    startCommand: node backBien/server.js

    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false

    autoDeploy: true
