services:
  - type: web
    name: farmacia-bienestar
    env: node
    plan: free

    # Comandos de build para backend y frontend
    buildCommand: |
      cd backFarm
      npm install
      cd ../frontFarm
      npm install
      npm run build -- --configuration production

    # Comando para iniciar tu server.js unificado
    startCommand: node backFarm/server.js

    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false  # La agregas en el panel de Render

    autoDeploy: true
