services:
  - type: web
    name: farmacia-bienestar
    env: node
    plan: free

    buildCommand: npm run build

    startCommand: node backBien/server.js

    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false

    autoDeploy: true
