services:
  - type: web
    name: farmacia-bienestar
    env: node
    plan: free

    # Comandos de build para backend y frontend
    buildCommand: |
      cd backBien
      npm install
      cd ../frontFarm
      npm install
      npm run build -- --configuration production
      mkdir -p ../backBien/public
      cp -r dist/front-farm/* ../backBien/public/

    # Comando para iniciar tu server.js unificado
    startCommand: node backBien/server.js

    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false  # La agregas en el panel de Render

    autoDeploy: true
