require("./inventarioPortatil.controller.test");
require("./sessionSecurity.test");
require("./surtidoFarmacia.controller.test");
require("./reporteSurtidos.controller.test");
require("./certificadosMedicos.controller.test");
require("./ajusteInventario.ubicacionFarmacia.test");
require("./exportarViabilidad.test");
require("./controlInventario.test");
require("./ventaInventario.test");
